quarkus.http.root-path=/api
quarkus.http.cors.enabled=true
quarkus.http.cors.origins=*

quarkus.log.console.enable=true
quarkus.log.level=INFO
quarkus.log.console.level=INFO

quarkus.http.access-log.enabled=true
quarkus.http.access-log.pattern=common

problem.base-url=http://localhost:8080